version: '3'

services:
  db:
    image: mysql:8.0.21
    container_name: ecommerce_db
    platform: linux/x86_64
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - net

  backend:
    image: node:16.14
    container_name: ecommerce_backend
    platform: linux/x86_64
    tty: true
    stdin_open: true
    working_dir: /app-backend
    command: bash -c "npm install && chown -R root /app-backend && npm start"
    restart: always
    volumes:
      - ./backend:/app-backend
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      MYSQL_DATABASE: ecommerce_db
      MYSQL_PORT: 3306
      PORT: 3001
      JWT_SECRET: jwt_secret
    networks:
      - net

  frontend:
    image: node:16.14
    container_name: ecommerce_frontend
    tty: true
    stdin_open: true
    working_dir: /app-frontend
    command: bash -c "npm install && npm start"
    restart: always
    volumes:
      - ./frontend:/app-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - net

networks:
  net:
    driver: bridge
